import Head from 'next/head'
import client from '../apollo-client'
import { gql } from '@apollo/client'
import Link from 'next/link'
import Rocket from '../Images/rocket.jpg'
export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Missions {
        launchesPast(limit: 10) {
          mission_id
          mission_name
          launch_date_local
          rocket {
            rocket_name
            rocket_type
            rocket {
              id
            }
          }
          links {
            flickr_images
            article_link
          }
        }
      }
    `,
  });

  return {
    props: {
      missions: data.launchesPast,
    },
  };
}

export default function Home({ missions }) {

  console.log(Rocket);
  return (
    <div className='missions-container'>
      <div className='mission-text'>
        <h1>Missions</h1>

      </div>
      <Head>
        <title>SpaceX Missions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='missions'>
        {missions?.map(({ launch_date_local, mission_name, rocket, links }) => (
          <Link href={`rockets/${rocket?.rocket?.id}`}>
            <a>
              <div className='mission-item'>
                {links.flickr_images.length !== 0 ? (
                  <div className="img" style={{ content: `url(${links.flickr_images})` }}></div>
                ) : (
                  <img src={Rocket.src} ></img>
                )}
                <h2>{mission_name}</h2>
                <h4>Launch date:{launch_date_local}</h4>
                <h5>Rocket: {rocket.rocket_name}</h5>
              </div>
            </a>
          </Link>
        ))}

      </div>
    </div>
  )
}
